# Generated by Django 4.2.23 on 2025-08-04 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_profile_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleanliness', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=50)),
                ('sleep_schedule', models.CharField(choices=[('Early', 'Early'), ('Late', 'Late')], max_length=50)),
                ('food', models.CharField(choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg'), ('Eggetarian', 'Eggetarian')], max_length=50)),
                ('pets', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('smoking', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('study_habits', models.CharField(max_length=50)),
                ('social_life', models.CharField(max_length=50)),
                ('partying', models.CharField(max_length=50)),
                ('guest_frequency', models.CharField(max_length=50)),
                ('noise_tolerance', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
